### PR TITLE
feat: add signup and login page

### PR DESCRIPTION
**Pull request by devdeadviz**
# Change Logs
## Screenshots
Screenshot (218)
Screenshot (216)

### CODE REVIEW

**Review by yashpatel1797 — APPROVED** [review]
1. Code looks clean.
2. file structure is good.

**Review by ivinayakg — APPROVED** [review]
Go ahead and merge these components, they are good.

**Review by yashpatel1797 — APPROVED** [review]
You can add first name, last name, confirm password in sign up form.

**Comment by devdeadviz** [comment]
> You can add first name, last name, confirm password in sign up form.

Sure, will add that!

**Pull request merged**
